apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: opentelemetry
spec:
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      namespace: opentelemetry
      labels:
        app: collector    
    spec:
      containers:
      - name: collector
        image: otel/opentelemetry-collector-contrib:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
            - name: metrics
              containerPort: 8889
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
#(for use with Kinesis)              
            # - name: kinesis
            #   containerPort: 8443
            #   protocol: TCP
        volumeMounts:
        - name: otel-config
          mountPath: /etc/otelcol-contrib
          readOnly: true
      volumes:
      - name: otel-config
        configMap:
          name: otel-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: opentelemetry
  name: collector
  annotations:  
      prometheus.io/path: /metrics
      prometheus.io/port: "8889"
      prometheus.io/scrape: 'true'  
spec:
  selector:
    app: collector
  ports:
    - name: prometheus-metrics
      port: 8889
      targetPort: 8889
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http      
      port: 4318
      targetPort: 4318            
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: opentelemetry
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

      # (for use with Kinesis)
      # awsfirehose:
      #   endpoint: 0.0.0.0:8443
      #   record_type: cwmetrics
      #   access_key: "otel123"
      #   tls:
      #     cert_file: "/etc/otelcol-contrib/certificate.crt"
      #     key_file: "/etc/otelcol-contrib/privateKey.key" 
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      logging:
        verbosity: detailed

    processors:
      batch: {}

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]

  # (for use with Kinesis)
  # certificate.crt: |-
  #   -----BEGIN CERTIFICATE-----
  #   MIIELzCCAxegAwIBAgISA7F0O7RDptQs52yd07Idn/WzMA0GCSqGSIb3DQEBCwUA
  #   MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
  #   EwJSMzAeFw0yMzA3MjYxNjE0MzBaFw0yMzEwMjQxNjE0MjlaMCExHzAdBgNVBAMT
  #   Fm90ZWwuY3Vyc29kZWF3cy5jb20uYnIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
  #   AARx2sNvlxjKhGO7e62MKhqvViuHfRxDQgiCRd5wXiwo7JIVVteRqa+QustVujWU
  #   I7PIperWGd3xcj1tcm/SdpNQo4ICGTCCAhUwDgYDVR0PAQH/BAQDAgeAMB0GA1Ud
  #   JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
  #   BBQyQY8isRRPlfRVb4Wbsg5MfPFJoTAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDm
  #   LmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzAh
  #   BgNVHREEGjAYghZvdGVsLmN1cnNvZGVhd3MuY29tLmJyMBMGA1UdIAQMMAowCAYG
  #   Z4EMAQIBMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHYAejKMVNi3LbYg6jjgUh7p
  #   hBZwMhOFTTvSK8E6V6NS61IAAAGJkzHwlwAABAMARzBFAiAPgNG0J35Ss90acz5t
  #   eZ+JTIsvcxHVqlJkthexBzlq5wIhAM5tVw3cH6BILMcCmW8+XsGJeFlIeWgXklFQ
  #   0s52vCrOAHcA6D7Q2j71BjUy51covIlryQPTy9ERa+zraeF3fW0GvW4AAAGJkzHw
  #   aPn/IGtOlkUKxOPwo6LdRTWjOBdRUSHxahq3VKaaD5WR4Pykz6uQhbLL3Kv8pDsU
  #   4gwX6RSuvxvnAPWzYKeA1oXhw5vD34dK4edeJQHEsZ5SCPqqFR4PSXSTNaOBEm9R
  #   r9qPSa92qxVTdgpjmImDqJx+5w==
  #   -----END CERTIFICATE-----
  #   -----BEGIN CERTIFICATE-----
  #   MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
  #   TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
  #   cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
  #   RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
  #   AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
  #   R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
  #   sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
  #   NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
  #   Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
  #   /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
  #   AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
  #   Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
  #   FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
  #   AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
  #   Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
  #   gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
  #   PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
  #   avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
  #   yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
  #   yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
  #   hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
  #   HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
  #   MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
  #   nLRbwHOoq7hHwg==
  #   -----END CERTIFICATE-----
  #   -----BEGIN CERTIFICATE-----
  #   MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
  #   MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
  #   DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
  #   TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
  #   cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
  #   AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
  #   ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
  #   wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
  #   LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
  #   SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
  #   PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
  #   TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
  #   SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
  #   c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
  #   +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
  #   ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
  #   b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
  #   U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
  #   MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
  #   5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
  #   9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
  #   WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
  #   he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
  #   Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
  #   -----END CERTIFICATE-----

  # privateKey.key: |-
  #   -----BEGIN PRIVATE KEY-----
  #   MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg55eqx0WdL1Apxa9I
  #   QgiCRd5wXiwo7JIVVteRqa+QustVujWUI7PIperWGd3xcj1tcm/SdpNQ
  #   -----END PRIVATE KEY-----              